import "../styles/globals.css";
import { ChakraProvider } from "@chakra-ui/react";
import "tailwindcss/tailwind.css";
import Navbar from "../components/Navbar";
import Head from "next/head";
import Footer from "../components/Footer";

export default function App({ Component, pageProps }) {
  const Layout = Component.layout || (({ children }) => <>{children}</>);
  return (
    <Layout>
      <Head>
        <title>Scream Your Heart Out</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ChakraProvider>
        {/* <div className="flex flex-col min-h-[100vh] bg-[gray]"> */}
          <Navbar />
          <Component {...pageProps}  />
          <Footer />
        {/* </div> */}
      </ChakraProvider>
    </Layout>
  );
}
